# permalink > defines the blog post url-convention
permalink: /news/:title
# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
pygments: true

#Prose.io editing info
repo_name: open-source-program-template
branch: gh-pages
#GitHub organization name *or* username
gh_org: virtix
prose_url: http://prose.io
site_url: http://if.io/open-source-program-template
media: assets/img


# Name of the site
name: Design a next Generation adventure
description: website danga
subtitle: A set of templates and artifacts to support open source programs 

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/open-source-program-template'

# Author/Organization info to be displayed in the templates
author:
  name: Thomas Jefferson 
  url: http://localhost:4000

# ------------------------------------------------------------------
#   Navigation
#   List links that should appear in the site sidebar here
#   "pages" is a directory to keep web content that are not posts
# ------------------------------------------------------------------
navigation:
- text: Home
  url: index.html
  internal: true
- text: Guiding Principles
  url: pages/guiding_principles.html
  internal: true
- text: Open Source Policy
  url: pages/oss_policy.html
  internal: true
- text: News
  url: pages/news.html
  internal: true
- text: Open By Default
  url: pages/open_by_default.html
  internal: true
- text: FAQs
  url: pages/faq.html
  internal: true 
- text: Processes &amp; Procedures
  url: pages/workflows.html
  internal: true
- text: References
  url: pages/references.html
  internal: true
## You should remove or comment these next few lines when going live 
- text: How to configure this site
  url: pages/howto.html
  internal: true
